version: "3.7"
services:
    web:
        build: .
        restart: always
        ports:
            - "8000:80"
            - "8080:443"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux:2017-latest"
        container_name: db-server
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"